### ISSUE TITLE
data_formatting

### ISSUE THREAD

**Issue by che1219** [kirchhausenlab/incasem#8]
Hi,

I have installed all the modules and code. I am at the part to convert the tiff to Zarr. 

python 00_image_sequences_to_zarr.py -i ~/incasem/data/my_new_data -f ~/incasem/data/my_new_data.zarr

However, I got the error:

    ds = daisy.prepare_ds(output_file,
                          output_dataset,
                          total_roi=metric_roi,
                          voxel_size=voxel_size,
                          write_size=voxel_size * daisy.Coordinate(chunks),
                          dtype=dtype,
                          compressor={'id': 'zlib', 'level': 3})

Traceback (most recent call last):
  File "00_image_sequences_to_zarr.py", line 135, in <module>
    main()
  File "00_image_sequences_to_zarr.py", line 119, in main
    fos.utils.image_sequence_to_zarr(
  File "/home/chongyuh/incasem/incasem/utils/image_sequence_to_zarr.py", line 255, in image_sequence_to_zarr
    ds = daisy.prepare_ds(output_file,
AttributeError: module 'daisy' has no attribute 'prepare_ds'

I wonder if there is a way to solve this problem.
Thank you!

**Comment by bentaculum** [comment]
Thanks for filing the issue.
I pinned the dependency on `daisy` to version 0.2.1 in 5d4d337 to solve it.

You can either update `incasem` with `git pull` and go through the installation process one more time in a fresh conda environment, or simply downgrade your `daisy` installation using pip.
